version: "3.8"

services:
  cover_letter_api:
    image: mikkak/letterix_cover_letter_api:latest
    container_name: cover_letter_api
    env_file:
      - cover_letter_api/.env
    ports:
      - "8081:8080"
    volumes:
      - ./src:/app/src
    
  letterix_db:
    image: postgres:latest
    container_name: letterix_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: letterix

  letterix_backend:
    image: mikkak/letterix_backend:latest
    container_name: letterix_backend
    env_file:
      - letterix_backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - letterix_db