name: api_gateway_CI_CD

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - main
    paths:
      - Letterix_API/api-gateway/**
  pull_request:
    branches:
      - main
    paths:
      - Letterix_API/api-gateway/**
env:
  REGISTRY: registry.alasfood.ch

jobs:
  builMicroservices:
    name: Docker build and push microservices
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: Build the API_gateway image
      working-directory: ./Letterix_API/api-gateway
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/letterix_api_gateway:latest
      
    - name: Push api_gateway
      if: github.event_name != 'pull_request'
      run: docker push ${{ env.REGISTRY }}/letterix_api_gateway:latest
      
  #deploy:
    #name: deploy to server
    #runs-on: ubuntu-latest
    #needs: [builMicroservices, buildFrontend]
    #steps:
    #- name: deploy on server
      #uses: appleboy/ssh-action@master
      #with:
          #host: ${{ secrets.SSH_HOST }}
          #username: ${{ secrets.SSH_USER }}
          #key: ${{ secrets.SSH_KEY }}
          #port: 6069
          #script: pwd
