name: config_server_CI_CD

on:
  push:
    branches:
      - main
    paths:
    - ./Letterix_API/config-server
  pull_request:
    branches:
      - main
    paths:
    - ./Letterix_API/config-server
env:
  REGISTRY: registry.alasfood.ch

jobs:
  builMicroservices:
    name: Docker build and push microservices
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
    - name: checkout repo
      uses: actions/checkout@v3
  
    
    - name: Build the config_server image
      working-directory: ./Letterix_API/config-server
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/letterix_config_server:latest
    
    - name: Push config_server
      if: github.event_name != 'pull_request'
      run: docker push ${{ env.REGISTRY }}/letterix_config_server:latest

      
  #deploy:
    #name: deploy to server
    #runs-on: ubuntu-latest
    #needs: [builMicroservices, buildFrontend]
    #steps:
    #- name: deploy on server
      #uses: appleboy/ssh-action@master
      #with:
          #host: ${{ secrets.SSH_HOST }}
          #username: ${{ secrets.SSH_USER }}
          #key: ${{ secrets.SSH_KEY }}
          #port: 6069
          #script: pwd
