name: frontend_CI_CD

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
env:
  REGISTRY: registry.alasfood.ch

jobs:
  buildFrontend:
    name: Docker build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Build the application
        working-directory: ./frontend
        run: yarn build .

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./frontend/build/
          
      - name: Build the frontend image
        working-directory: ./frontend
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/letterix_frontend:latest 
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push frontend
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.REGISTRY }}/letterix_frontend:latest
        
  #deploy:
    #name: deploy to server
    #runs-on: ubuntu-latest
    #needs: [builMicroservices, buildFrontend]
    #steps:
    #- name: deploy on server
      #uses: appleboy/ssh-action@master
      #with:
          #host: ${{ secrets.SSH_HOST }}
          #username: ${{ secrets.SSH_USER }}
          #key: ${{ secrets.SSH_KEY }}
          #port: 6069
          #script: pwd
